import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Montserrat } from "next/font/google";
// import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./context/AuthContext";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import 'mapbox-gl/dist/mapbox-gl.css';
import "@fortawesome/fontawesome-free/css/all.min.css";
import Preloader from "./components/Preloader";
import ChatBox from "./components/chatbox";
import { CartProvider } from "./components/CartContext";


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
      >
        <AuthProvider>
        <CartProvider>
        <Preloader />
          <Header />
          {/* <Toaster
            position="top-right"
            reverseOrder={false}
            toastOptions={{
              className: "bg-black text-white",
              style: {
                fontSize: "16px",
                fontFamily: "var(--font-geist-sans)",
              },
            }}/> */}
          
          {children}
          <ChatBox />
          <Footer />
          <ToastContainer
            position="top-right"
            autoClose={3000}
            style={{ marginTop: "120px" }}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
